name: CI/CD and Deploy

on:
  # Disabled due to https://linear.app/replay/issue/PRO-1001/nutnew-broken-builds
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: CI/CD (and deploy on main)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build
        with:
          sentry-auth-token: ${{ github.ref == 'refs/heads/main' && secrets.SENTRY_AUTH_TOKEN || '' }}

      - name: Run type check
        run: pnpm run typecheck

      - name: Run ESLint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          command: pages deploy
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
